language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: pytest tests

before_deploy:
  - nvm install 5.9.1
  - npm i -g serverless@1.8.0

deploy:
  skip_cleanup: true
  provider: script
  script: bin/deploy.sh
