# For full config options, check the docs:
#    docs.serverless.com

service: xchatbot

provider:
  name: aws
  runtime: python2.7
  region: us-east-1
  memorySize: 256 # optional, default is 1024
  timeout: 60 # optional, default is 6
  versionFunctions: false # optional, default is true

package:
  include:
    - vendored
    - nltk_data
  exclude:
    - .tox/**
    - .env
    - .cache/**
    - tests/**

functions:
  webhook_post:
    handler: lambda_handler.webhook_lambda_handler
    environment:
      TELEGRAM_API_KEY: ${env:TELEGRAM_API_KEY}
      HOME: /var/task
      SLS_DEBUG: "*"
    events:
      - http:
          path: /telegram_webhook
          method: post
  webhook_get:
    handler: lambda_handler.webhook_lambda_handler
    environment:
      TELEGRAM_API_KEY: ${env:TELEGRAM_API_KEY}
      HOME: /var/task
      SLS_DEBUG: "*"
    events:
      - http:
          path: /telegram_webhook
          method: get
